### ISSUE TITLE
The website shows unsecure

### ISSUE THREAD

**Issue by Today100** [jessvb/zhorai#28]

**Comment by jessvb** [comment]
Thanks for the heads up @Today100. This happens periodically because I can't seem to get the Zhorai Let's Encrypt certificates to auto-renew within the Docker container. If you or anyone else has expertise in this area, it would be great to connect to try to fix this...

I used [this medium article](https://pentacent.medium.com/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71) to initially set up the certificates.

Alternatively, [ReadyAI also hosts a version of Zhorai](https://zhorai.readyai.org/) that doesn't show unsecure.

**Comment by Today100** [comment]
Thank you so much for replying! ReadyAI hosts a great version of Zhorai. Would you like to add it to the Readme file so that other people could go to the right website?
